# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('request_duration_ms', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField()),
                ('request_type', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditlogtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, db_column='ipAddress', max_length=256, null=True)),
                ('executetime', models.CharField(blank=True, db_column='ExecuteTime', max_length=256, null=True)),
                ('requesttime', models.CharField(blank=True, db_column='RequestTime', max_length=256, null=True)),
                ('responsecode', models.CharField(blank=True, db_column='ResponseCode', max_length=256, null=True)),
                ('requesturl', models.CharField(blank=True, db_column='RequestUrl', max_length=256, null=True)),
            ],
            options={
                'db_table': 'AuditLogTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryId', primary_key=True, serialize=False)),
                ('categorydescription', models.TextField(db_column='categoryDescription')),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorytest',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryId', primary_key=True, serialize=False)),
                ('categorydescription', models.TextField(db_column='categoryDescription')),
            ],
            options={
                'db_table': 'CategoryTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('email', models.CharField(blank=True, max_length=11, null=True)),
                ('orderid', models.IntegerField(blank=True, db_column='orderId', null=True)),
                ('status', models.CharField(blank=True, max_length=11, null=True)),
                ('username', models.CharField(blank=True, db_column='userName', max_length=11, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateField(blank=True, db_column='timeStamp', null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered')),
                ('priceeach', models.FloatField(db_column='priceEach')),
            ],
            options={
                'db_table': 'OrderLine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderlineCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered')),
                ('priceeach', models.FloatField(db_column='priceEach')),
            ],
            options={
                'db_table': 'OrderLine_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderlinetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered')),
                ('priceeach', models.FloatField(db_column='priceEach')),
            ],
            options={
                'db_table': 'OrderLineTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='orderId', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='orderDate', null=True)),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('discontinued', models.IntegerField()),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstest',
            fields=[
                ('orderid', models.AutoField(db_column='orderId', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='orderDate', null=True)),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'OrdersTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='productId', primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=255, null=True)),
                ('productdescription', models.TextField(blank=True, db_column='productDescription', null=True)),
                ('quantityinstock', models.IntegerField(db_column='quantityInStock')),
                ('buyprice', models.FloatField(db_column='buyPrice')),
                ('discontinued', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producttest',
            fields=[
                ('productid', models.AutoField(db_column='productId', primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, db_column='productCode', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=255, null=True)),
                ('productdescription', models.TextField(blank=True, db_column='productDescription', null=True)),
                ('quantityinstock', models.IntegerField(db_column='quantityInStock')),
                ('buyprice', models.FloatField(db_column='buyPrice')),
                ('discontinued', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ProductTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='customerName', max_length=255)),
                ('contactfirstname', models.CharField(blank=True, db_column='contactFirstName', max_length=255, null=True)),
                ('contactlastname', models.CharField(blank=True, db_column='contactLastName', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('addressline1', models.CharField(blank=True, db_column='addressLine1', max_length=255, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userstest',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='customerName', max_length=255)),
                ('contactfirstname', models.CharField(blank=True, db_column='contactFirstName', max_length=255, null=True)),
                ('contactlastname', models.CharField(blank=True, db_column='contactLastName', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('addressline1', models.CharField(blank=True, db_column='addressLine1', max_length=255, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'UsersTest',
                'managed': False,
            },
        ),
    ]
