# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='auditlogtest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categorytest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderlinecopy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderlinetest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderstest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producttest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userstest',
            options={'managed': True},
        ),
    ]
