# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20160715_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='orderid',
            field=models.ForeignKey(db_column='orderId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='productid',
            field=models.ForeignKey(db_column='productId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinecopy',
            name='orderid',
            field=models.ForeignKey(db_column='orderId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinecopy',
            name='productid',
            field=models.ForeignKey(db_column='productId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinetest',
            name='orderid',
            field=models.ForeignKey(db_column='orderId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlinetest',
            name='productid',
            field=models.ForeignKey(db_column='productId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Category'),
        ),
        migrations.AddField(
            model_name='producttest',
            name='categoryid',
            field=models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Category'),
        ),
        migrations.AlterField(
            model_name='orderlinecopy',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(db_column='userId', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='productapp.Users'),
            preserve_default=False,
        ),
    ]
